-- create database new_lco;

-- use new_lco;

-- CREATE TABLE USERS(
--     ID INT AUTO_INCREMENT PRIMARY KEY,
--     NAME VARCHAR(30),
--     EMAIL VARCHAR(60)
-- );

-- CREATE TABLE PURCHASES(
--      ID INT AUTO_INCREMENT PRIMARY KEY,
--      ORDER_DATE DATE,
--      AMOUNT INT,
--      USER_ID INT,
--      FOREIGN KEY (USER_ID) REFERENCES USERS(ID) 
-- );

-- INSERT INTO USERS(NAME, EMAIL) 
-- VALUES ('THOR','THOR@gmail.com' ),
-- ('TONY', 'TONY@GMAIL.COM'),
-- ('PETER', 'SPIDER@GMAIL.COM')
-- ;

INSERT INTO PURCHASES(ORDER_DATE, AMOUNT, USER_ID)
VALUES('1999-08-31','99999','1');